# This is a basic workflow to help you get started with Actions

name: Deploy KenMacPherson Website

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    # deploy to atlantic.net kenmacpherson.com
    # sshpass -p "notrequired using keys"
    # echo "Deploying scp to kenmacpherson IP"
    # sshpass -p "password" scp -rp ~/clone/* root@104.245.39.145:/var/www
    # echo "completed scp of files"
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "website/*"
        target: "/var/www"   

    - name: copy website nginx conf file 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "default, macphersonformayor.com.conf, warren.fyi.conf, tcpanthers.org.conf, heavensentdoula.com.conf"
        target: "/etc/nginx/sites-available" 

    - name: copy warren.fyi via ssh password
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "warren.fyi/*"
        target: "/var/www"   

    - name: copy tcpanthers.org via ssh password
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "tcpanthers.org/*"
        target: "/var/www"      

    - name: copy macphersonformayor.com via ssh password
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "macphersonformayor.com/*"
        target: "/var/www"      

    - name: copy heavensentdoula.com via ssh password
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "heavensentdoula.com/*"
        target: "/var/www"      

    - name: copy warrendeservesbetter.org via ssh password
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "warrendeservesbetter.org/*"
        target: "/var/www"      


    # - uses: webfactory/ssh-agent@v0.4.0
    #   with:
    #       ssh-private-key: ${{ secrets.KEY }}
    #  

    - name: shell run ssh remote command systemctl restart nginx 
      shell: bash
      env:
        KEY: ${{ secrets.KEY }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo "$KEY" > $GITHUB_WORKSPACE/cred; cat $GITHUB_WORKSPACE/cred 
        echo "$KEY" > ~/cred; cat ~/cred 
        ssh -i "$GITHUB_WORKSPACE/cred" $USERNAME@$HOST "/etc/init.d/nginx restart"
